### ISSUE TITLE
ShopLogo component

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction-component-library#104]
# ShopLogo Component
## Overview / Summary
Create ShopLogo component - This component should display a site logo or the shop's name as a fallback

## Expected use cases
This component will be used to render the shops logo any time the checkout is rendered

### Where should this component live
This component should be created in the Reaction Component Library

<img width="368" alt="image" src="https://user-images.githubusercontent.com/1203639/42116756-00ea28e4-7bb6-11e8-9d5d-2c827dcc7fe9.png">

```jsx
// Pseudo-markup for the checkout nav
<div>
    <img src="shop_logo.png alt="Shop Name />
    ||
    Shop Name
</div>
```

### Props
```js
propTypes: {
  shopLogoUrl: PropTypes.string,
  shopName: PropTypes.string
}
```

### Render Criteria
The ShopLogo should be rendered in the header and with the Checkout Page generally.

#### Normal
Zeplin:
https://app.zeplin.io/project/5afc82f5e8d73e250ff9d855/screen/5b02f4fa90d3b184213318da

#### Normal
Zeplin:
https://app.zeplin.io/project/5afc82f5e8d73e250ff9d855/screen/5b02f55b5650607e22fdbaf6

**Comment by aldeed** [comment]
@spencern In the designs, I believe this is intended to be the same logo image that appears in the upper left of other pages. We don't actually have the logo image appearing in the header of the starterkit yet, so I vote to change this issue to be "Create ShopLogo component", and then we'll use it both in the standard header and on the checkout page. It could take the shopName string, too, and render that as a fallback if there is no logo.

**Comment by willopez** [comment]
@spencern @aldeed I have updated the issue's description to match Eric suggestion, and it should be in the component library correct?
