### ISSUE TITLE
Checkout Action Complete

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction-component-library#112]
# Checkout Action Complete

### Summary description of UI component
This component should be rendered for any completed checkout actions.

### Rationale for why this component is necessary
This component abstracts the completed checkout action UI.

### Expected use cases
This component will be used in the checkout process for any completed checkout actions

### Where this component should be created
This component should be created in the component library

### Images / Designs of UI component in context
![image](https://user-images.githubusercontent.com/1203639/42176608-c055f6b8-7de6-11e8-937f-2a1b434f2852.png)

```jsx
// Pseudo-markup for the Completed Checkout Action
<div>
  <span>Label</span>
  <div>Content</div>
  <Button>Change</Button>
</div>
```

### Props
```js
propTypes: {
  label: PropTypes.string,
  content:PropTypes.instanceOf(Element),
  onChange: PropTypes.func
}
```

### Render Criteria
This component will be rendered for each completed checkout action

#### Normal
This prop only exists in a Normal state. Render the label, the content and the `change` button.
There are many Zeplin examples, any UI with a completed checkout step.
https://app.zeplin.io/project/5afc82f5e8d73e250ff9d855/screen/5b02f47216618fd82ceea667

In this example, the Shipping address and the Shipping method actions are both complete.

**Comment by kieckhafer** [comment]
@spencern @aldeed Should we be importing the button as a component, similar to how we do in the [CartEmptyMessage](https://github.com/reactioncommerce/reaction-component-library/blob/master/package/src/components/CartEmptyMessage/v1/CartEmptyMessage.js#L29) component? Or should we directly import the button here?

**Comment by kieckhafer** [comment]
@spencern @aldeed can you provide an example of what we expect to be passed down for the `content` prop?
