### ISSUE TITLE
Checkout Actions component

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction-component-library#113]
# Checkout Actions
## Overview / Summary
Create a Checkout Actions Component
This component should house the components that permit the user to make progress during a checkout.

## Expected use cases
This component will be used anytime the checkout page is rendered.

### Where should this component live
This component should be created in the component library.

## Images
<img width="749" alt="image" src="https://user-images.githubusercontent.com/1203639/42185608-bcde8688-7e06-11e8-8f76-7344db9a6c54.png">

```jsx
// Pseudo-markup for the checkout actions
<div>
  <AccountOrEmail />
  <CheckoutActionsList />
</div>
```

### Props
```js
propTypes: {
  checkoutEmail: PropTypes.string,
  accountEmail: PropTypes.string,
  cart: PropTypes.shape({}),
  stateFn: PropTypes.func
}
```

### Context
```js
// Action Components
AddressBook
ChooseShipmentMethods
ChoosePaymentMethod
CheckoutReview
```

### State
Each action in the `CheckoutActionsList` is responsible for it's own "active" state.
The state of each action should be determined by the `stateFn` which should combine the `cart` data with a list of actions which have been manually set to "active". This list should be kept in state on this component.

e.g. `activeComponents = ["someComponentIdentifier"]`

Whenever this list of active components or the cart changes, the function to determine state should be re-run and any changes re-rendered.

### Render Criteria
The CheckoutActions component should be rendered whenever the checkout page is rendered.

#### Normal
Zeplin:
https://app.zeplin.io/project/5afc82f5e8d73e250ff9d855/screen/5b02f470eefa9c371dd3c488

#### Normal
Zeplin:
https://app.zeplin.io/project/5afc82f5e8d73e250ff9d855/screen/5b02f55c91739e0f56ec27b7

**Comment by kieckhafer** [comment]
@spencern looks like the description on this ticket got cut off mid-sentence. Can you please update to provide those details?

**Comment by spencern** [comment]
@kieckhafer This is essentially a container for the list of checkout action components
