### ISSUE TITLE
Docs: Update Component Theming guide

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/reaction-component-library#118]
Type: **minor**

**Describe the bug**
Update [component theming guide](https://github.com/reactioncommerce/reaction-component-library/blob/master/docs/component-development-guidelines.md) to have examples and docs on using theme provider, theme variables inside of components and theme overrides.

**Comment by machikoyasuda** [comment]
Stuff to add to these docs:
- A note on using FontAwesome, like Checkbox and TextInput do

**Comment by aldeed** [comment]
@machikoyasuda We used font awesome as a quick placeholder, but I would prefer if we change everything to SVGs like I did with the TextInput clear button as a test: https://github.com/reactioncommerce/reaction-component-library/blob/master/package/src/components/TextInput/v1/TextInput.js#L172

I'll make an issue for this.
