### ISSUE TITLE
Button Groups - Design & Usage Guidelines

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction-component-library#13]
As a developer for Reaction or a member of the Reaction community, I should be able to get design guidelines on a component level for the icons component.

**Comment by cassytaylor** [comment]
Button group guidelines are available here: http://zpl.io/bP41n3y

**Comment by cassytaylor** [comment]
![button groups - guidelines](https://user-images.githubusercontent.com/36006187/36763008-6b42ba2c-1be3-11e8-9fed-4d91513b3693.png)
