### ISSUE TITLE
Docs: Document and publish Colors design guidelines

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-component-library#140]
Document color variables, usage and design guidelines

## Steps
1. Create a markdown file in the [`styleguide/src/sections/`](https://github.com/reactioncommerce/reaction-component-library/tree/master/styleguide/src/sections) folder by clicking [`Create a new file`](https://github.com/reactioncommerce/reaction-component-library/new/master/styleguide/src/sections)
2. Add guidelines into this markdown file
3. Scroll down and Click `Commit` with the `🔘 Create a new branch for this commit and start a pull request. ` turned on.
4. Keep editing that file.
5. Add the name of that file to the table of contents, here: https://github.com/reactioncommerce/reaction-component-library/blob/master/styleguide.config.js#L251

**Comment by rymorgan** [comment]
Color - zpl://screen?sid=5ab40ad441ffd6ee46ec97a0&pid=59305ed4ac6e641b8ea32f76

![guidelines - color](https://user-images.githubusercontent.com/20409254/43553757-6c341412-95a5-11e8-9284-68d7c5d3af20.png)
