### ISSUE TITLE
Docs: Document and publish Type design guidelines

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-component-library#142]
Document and publish Typography design guidelines

## Steps
1. Create a markdown file in the [`styleguide/src/sections/`](https://github.com/reactioncommerce/reaction-component-library/tree/master/styleguide/src/sections) folder by clicking [`Create a new file`](https://github.com/reactioncommerce/reaction-component-library/new/master/styleguide/src/sections)
2. Add guidelines into this markdown file
3. Scroll down and Click `Commit` with the `🔘 Create a new branch for this commit and start a pull request. ` turned on.
4. Keep editing that file.
5. Add the name of that file to the table of contents, here: https://github.com/reactioncommerce/reaction-component-library/blob/master/styleguide.config.js#L251

(Machiko can help with step #2)

## Content

- fontFamily
- font size scale
- font weights
- leading

**Comment by rymorgan** [comment]
Here's what we're thinking for type documentation. We need to find places insert the code approach. Aka how we build the scale, how it's built on 16px as a base but could be increased for larger screens. (not so much for smaller screens though). We can talk about how spacing is built from the base type unit in the spacing docs. 

zpl://screen?sid=5a8f6a16f0b8de12377819bf&pid=59305ed4ac6e641b8ea32f76

![typography](https://user-images.githubusercontent.com/20409254/43552586-ea50457e-959f-11e8-8f06-cc1e6bb0502a.png)
