### ISSUE TITLE
Design bugs: Minor styleguide design bugs

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-component-library#147]
- Fix magnifying glass
- Fix code whitespace
- Change CodeMirror to Yeti
- 

![](https://user-images.githubusercontent.com/20409254/43022616-afb74462-8c1c-11e8-8688-66f3dfba74dd.png)

**Comment by rymorgan** [comment]
Piling on to this issue with formatting updates needed for legibility/readability. 

Clean screenshot
![screencapture-deploy-preview-139-stoic-hodgkin-c0179e-netlify-2018-07-20-11_52_58](https://user-images.githubusercontent.com/20409254/43022616-afb74462-8c1c-11e8-8688-66f3dfba74dd.png)

Annotated screenshot
![styleguide-styleguid](https://user-images.githubusercontent.com/20409254/43022680-e62c8124-8c1c-11e8-92d0-52ec0d6908b1.png)
