### ISSUE TITLE
Select - Design & Usage Guidelines

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction-component-library#15]
As a developer for Reaction or a member of the Reaction community, I should be able to get design guidelines on a component level for the select component.

**Comment by spencern** [comment]
@cassytaylor @rymorgan can a select have an invalid state?

**Comment by cassytaylor** [comment]
@spencern actually yes, Selects can have an invalid state. I can add that to the documentation.

**Comment by cassytaylor** [comment]
Updated with error/invalid state styling.

**Comment by spencern** [comment]
@machikoyasuda is this finished?

**Comment by machikoyasuda** [comment]
@spencern All of these tickets for designers are now moved to here: https://github.com/reactioncommerce/design/issues
