### ISSUE TITLE
Icons: Remove use of Font Awesome

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction-component-library#154]
## Background

We used Font Awesome icons in a few components. To avoid having that dependency, we should change everything to use SVGs like I did with the TextInput clear button as a test: https://github.com/reactioncommerce/reaction-component-library/blob/master/package/src/components/TextInput/v1/TextInput.js#L172

## Work

- Find everywhere where `fa` or `fab` classes are used
- Find everywhere where Font Awesome fonts are used in pseudoelements

- Find the icons on https://fontawesome.com/icons and click Download SVG button for each
- Replace these icon elements with a React svg element based on the SVG you downloaded. You may have to adjust the capitalization of the SVG props. See https://reactjs.org/docs/dom-elements.html#all-supported-html-attributes

- Remove font awesome from docs and update docs to explain how to properly add an SVG icon for a component.
- Component injection: https://github.com/reactioncommerce/reaction-component-library/blob/815c823524e5bf4f891fff3417173869dd0f4174/styleguide/src/sections/InstallingandImporting.md#provide-the-components-context

## Components

1. Checkbox: checkmark pseudo-element
2. TextInput: gavel, thumbs-down, thumbs-up, check-circle, pied-piper
3. ErrorsBlock: exclamation-triangle

## Documentation

Document our Icon policy

**Comment by machikoyasuda** [comment]
cc @rymorgan

**Comment by spencern** [comment]
Centralize these in a `/util/svg` folder or similar spot.

**Comment by machikoyasuda** [comment]
From FontAwesome's icon download use policy:

```
You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
```

What I think we should do:
- For every component that uses a FontAwesome SVG, note that in the documentation page. Credit FontAwesome in that doc for that component.
- Add credit info in README.md
- Add credit info in a README.md in the `/util/svg` folder. 

Anything/anywhere else we should attribute icon credit?

**Comment by spencern** [comment]
@machikoyasuda I agree that we should add a credit section to the component docs and to our readmes.
