### ISSUE TITLE
Docs: Document ::focus circle design standards

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-component-library#155]
Set the focus ring to mimic the hover style
Don’t override the browser style

**Comment by machikoyasuda** [comment]
Ideas:

- The teal is not dark contrasted enough
- 2px, instead of 1px

**Comment by rymorgan** [comment]
Proposed ideas - We can keep it teal and change the color to @teal-500 (#447467). Also we can make it two pixels thick so color blind folks can see a change it thickness of the border. 

Other color options - 
@dark-blue-300 (#135471)
@reaction-blue-400 (#067CBC)

**Comment by aldeed** [comment]
I discovered this, which I think we should try, in addition to defining pleasing focus/outline styles: https://github.com/WICG/focus-visible/blob/master/explainer.md

**Comment by rymorgan** [comment]
@aldeed Love that idea.
