### ISSUE TITLE
Multi Select - Design & Usage Guidelines

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction-component-library#16]
As a developer for Reaction or a member of the Reaction community, I should be able to get design guidelines on a component level for the multi select component.

**Comment by cassytaylor** [comment]
Multi-select design guidelines: zpl.io/295jjed

**Comment by cassytaylor** [comment]
![multi-selects - guidelines](https://user-images.githubusercontent.com/36006187/36704076-e6ae296c-1b1b-11e8-9971-f5420bc3d42d.png)
