### ISSUE TITLE
TextInput: Icon size issue in text input component on docs.

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction-component-library#162]
Type: **major**

**Describe the bug**

The icon in text input grows as you shrink the viewport

**To Reproduce**

1. Go to https://stoic-hodgkin-c0179e.netlify.com/#!/TextInput
2. Scroll down to the bottom with the text input with the `x` button
3. Resize your window smaller
4. Witness the enlargement of the icon

**Expected behavior**

Icons should obey size constraints.

**Screenshots**

![textinput_ _reaction_design_system](https://user-images.githubusercontent.com/42217/43213798-5e95e4ac-8fec-11e8-8dba-6324b91d8ce1.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 10.13.6
 - Browser Chrome
 - Version 67.0.3396.99

**Comment by spencern** [comment]
I've seen this as well.

**Comment by aldeed** [comment]
I spent a lot of time getting the right combination of styles for the icon to resize properly with the field and the base font size, so when we fix this, we'll have to make sure we don't break those things. We should come up with a list of manual tests to do (or automatic visual regression if possible)
