### ISSUE TITLE
TextInput: Font family and size inconsistencies between single line and multiline text inputs

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction-component-library#163]
Type: **minor**

**Describe the bug**

Text size difference between single line and multi-line text inputs

**To Reproduce**

1. Go to https://stoic-hodgkin-c0179e.netlify.com/#!/TextInput
2. Input text into both single line and multi-line text inputs
3. Notice a visual difference. I used the [Whatfont](https://chrome.google.com/webstore/detail/whatfont/jabopobgcpjmedljpbcaablpmlmfcogm?hl=en) chrome plugin to get the exact details.

**Expected behavior**

Used font family, size, and weight should be the standard defaults across inputs and other components.

**Screenshots**

![textinput_ _reaction_design_system](https://user-images.githubusercontent.com/42217/43214806-3bab2e4a-8fef-11e8-8944-1771143f5506.png)

**Desktop (please complete the following information):**

- OS: Mac OS 10.13.6
- Browser Chrome
- Version 67.0.3396.99

**Comment by rymorgan** [comment]
Both the label and text font size should be .875rem/14px
See here - 
zpl://screen?sid=5a95a70a7553a3d94bbcc309&pid=59305ed4ac6e641b8ea32f76
