### ISSUE TITLE
Textfield - Design & Usage Guidelines

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction-component-library#18]
As a developer for Reaction or a member of the Reaction community, I should be able to get design guidelines on a component level for the textfield component.

**Comment by rymorgan** [comment]
Zeplin link - zpl.io/bW1Xg61

![text field - guidelines](https://user-images.githubusercontent.com/20409254/36762106-ea584690-1bd6-11e8-9255-0ca9f0e741ad.png)

**Comment by cassytaylor** [comment]
Documentation for Text areas - zpl.io/2poXOGy
![text area - guidelines](https://user-images.githubusercontent.com/36006187/36917002-cda598f2-1e12-11e8-84d2-853a4dde0402.png)
