### ISSUE TITLE
Checkbox - Design & Usage Guidelines

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction-component-library#19]
As a developer for Reaction or a member of the Reaction community, I should be able to get design guidelines on a component level for the checkbox component.

**Comment by cassytaylor** [comment]
Documentation is up on Zeplin here - http://zpl.io/bzYjeKA

**Comment by cassytaylor** [comment]
![controls - guidelines](https://user-images.githubusercontent.com/36006187/36819254-f16a1c5e-1ca5-11e8-9186-929e6d4d6e7e.png)
