### ISSUE TITLE
Toggle/Switch - Design & Usage Guidelines

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction-component-library#20]
As a developer for Reaction or a member of the Reaction community, I should be able to get design guidelines on a component level for the toggle/switch component.

**Comment by cassytaylor** [comment]
Toggle design guidelines are up on Zeplin here - zpl.io/bzYjeKA
![controls - guidelines](https://user-images.githubusercontent.com/36006187/36859052-80568c10-1d3a-11e8-8332-eb2fd91586c5.png)
