### ISSUE TITLE
Epic: SelectableList - Shipping Method, Address & Payment Method

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-component-library#203]
Type: **major**

## Component Library

- [x] - SelectableItem #149 
- [x] - SelectableList #148 

## Starterkit

- [x] - Shipping Methods #194

**Comment by aldeed** [comment]
@machikoyasuda @nnnnat Be sure to coordinate since the AddressList bridges this epic and reactioncommerce/reaction#4511
