### ISSUE TITLE
Production deployment checklist: designsystem.reactioncommerce.com

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-component-library#204]
- [x] Create designsystem.reactioncommerce.com
- [x] Every master deploy should update designsystem.reactioncommerce.com, currently master is deployed to http://stoic-hodgkin-c0179e.netlify.com/

**Comment by griggheo** [comment]
I looked more into this issue and even if we do the http to https redirection on our side, the browser still gets the SSL cert from netlify.com so users will be presented with an SSL error when they go to https://designsystem.reactioncommerce.com.

I think the solution is to configure netlify with what they call a Custom Domain: https://www.netlify.com/docs/custom-domains

**Comment by griggheo** [comment]
There may also be a chance this will work if we handle the SSL termination on the Cloudflare side. They will take up to 24 hours to provision SSL certificates so I will try again tomorrow.

**Comment by griggheo** [comment]
Update: I created a custom domain in Netlify called designsystem.reactioncommerce.com. Netlify automatically provisioned Let's Encrytp SSL certificates for that domain. They also seem to be doing the automatic redirection from http to https. Please try both http://designsystem.reactioncommerce.com and https://designsystem.reactioncommerce.com. They should work as expected at this point.

**Comment by machikoyasuda** [comment]
Woohoo!
