### ISSUE TITLE
Component pages don't load in IE11

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction-component-library#207]
Type: **critical**

**Describe the bug**

Component docs in the styleguide don't load in IE11.

**To Reproduce**

1. Download and extract windows 10 VM for Virtualbox: https://developer.microsoft.com/en-us/windows/downloads/virtual-machines
1. Download and install https://www.virtualbox.org/wiki/Downloads for your host system
1. Double click on the `.ovf` file from the image, and wait for it to finish copying
1. Run the virtual machine
1. Open edge and go to a component page in the styleguide https://stoic-hodgkin-c0179e.netlify.com/#!/Field
1. Click on the `...` menu to the top right of the edge browser to reveal a menu
1. Click on `Open with Internet Explorer`
1. You should see the error in the screenshot

**Expected behavior**

The page should load and components should work in IE11 if IE11 is our minimum target for the windows-only browsers.

**Screenshots**

![screen shot 2018-08-09 at 9 39 19 am](https://user-images.githubusercontent.com/42217/43914034-90165d42-9bbb-11e8-94c6-ffd1993c9f70.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 version 1803
 - Browser IE11
 - Version 11.112.17134.0

**Comment by aldeed** [comment]
First step to fix this is to add and import babel-polyfill in the styleguide deps (not the package deps). Then see if other changes are needed to the components.
