### ISSUE TITLE
Create a Link component

### ISSUE THREAD

**Issue by dancastellon** [reactioncommerce/reaction-component-library#212]
# Component Name
Link

### Summary description of UI component
A component that renders a simple link.

### Rationale for why this component is necessary
Links are handled differently in Storefront vs the main Reaction app. Create a simple Link component that outputs an `<a href="...">...</a>` that will be overridden in both apps via the component context. This will allow both apps to define a custom Link component that handles navigation appropriately (NextJS vs React Router).

### Expected use cases
See above.

### Images / Designs of UI component in context
No style. Simply outputs an `<a href="...">...</a>`

### React State
No state needed.

## Props
```
static propTypes = {
    /**
     * The contents of the link, such as text, icons, or any combination of React and HTML components
     */
    children: PropTypes.node.isRequired,
    /**
     * The URL the link should navigate to
     */
    href: PropTypes.string.isRequired,
    /**
     * Called with a single event parameter when a user clicks the link
     */
    onClick: PropTypes.func.isRequired
  };
```

### Render Criteria
This component will be rendered as part of a new `<CatalogGrid />` component

### Breakpoints
N/A

#### Normal
Just a basic link.

**Comment by aldeed** [comment]
Makes sense
