### ISSUE TITLE
Update CartItem(s) to be able to hide quantity input and "remove" button

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction-component-library#221]
Type: **minor**

**Describe the issue**
Add more configuration options to the `CartItems` and `CartItem` component to hide both the quantity input and remove buttons, creating a read-only list of cart items.

**Screenshots**
No remove button
![guest_checkout_-_accordion_-_enter_shipping_address_-_error_-_storefront_-_zeplin](https://user-images.githubusercontent.com/42217/43918563-3e4f4c14-9bc8-11e8-92cb-469b029f26db.png)

No remove button or quantity input
![guest_checkout_-_accordion_-_order_review_-_storefront_-_zeplin](https://user-images.githubusercontent.com/42217/43918555-39a3d982-9bc8-11e8-856e-28f22d34c6c7.png)

**Comment by spencern** [comment]
A `readonly` version of this component is a great idea @mikemurray 👍
