### ISSUE TITLE
Add "isCommercial" checkbox to AddressForm component

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/reaction-component-library#234]
Type: **minor**

**Enhancement**
So we can replace the current RC AddressBook form with the new comp-lib AddressForm we'll need to add the `isCommercial` checkbox field at the bottom of the form. Not sure if this field would be required on all address entries or only within the old meteor app so I'm planning on making this an optional field, that is hidden by default but displays when an `isCommercialField={true}` prop is enabled.

@cassytaylor  I think this is the same deal as the #229 I'll add the field, get it working then we can hammer out the design during PR review.

**Comment by spencern** [comment]
@cassytaylor @nnnnat some shipping providers have different shipping schedules and prices for commercial addresses.

**Comment by aldeed** [comment]
I agree there should be a boolean prop for whether to show it because for a billing address or possibly some types of shop addresses it won't be necessary.
