### ISSUE TITLE
SelectableList: Mobile - Truncate label to 2 lines

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-component-library#235]
Type: **minor**

**Describe the bug**
<img width="427" alt="screen shot 2018-08-17 at 12 20 49 pm" src="https://user-images.githubusercontent.com/3673236/44284856-04e79200-a218-11e8-81eb-de31cd85c102.png">

**To Reproduce**
1. https://deploy-preview-210--stoic-hodgkin-c0179e.netlify.com/#!/SelectableList
2. Open on phone or mobile mode

**Expected behavior**
Truncate to 2 lines

**Comment by cassytaylor** [comment]
@spencern, it would preserve the entire address except for the remainder that doesn't fit on 2 lines of text within the container - so the user would still see the name, street address, apartment number, etc. with the information likely to be cut off being the state/region, postal code, and country. 

The customer would have enough to go on with the name and street address (ie, home address, PO box, etc.) that they would be able to select the correct address – and the address would be shown in full on the other steps throughout checkout.

**Comment by spencern** [comment]
A few more complications @cassytaylor 

Right now discussing truncating the label to 2 lines because of a specific implementation of the SelectableList in the address book. This decision will have impact on _all_ selectable lists that we create throughout the application. Some lists may require that all information is displayed for each item.

How should this work with increased or decreased text sizes? Screen readers?

**Comment by aldeed** [comment]
I would vote for default behavior to expand the height and keep the top line of text aligned with the radio/checkbox. Then there can be a `shouldTruncateText` prop where you can opt in to a no-wrap behavior.

**Comment by cassytaylor** [comment]
@spencern Hmmm, I'm gonna have to discuss with @rymorgan to make a call on this one...

**Comment by rymorgan** [comment]
@aldeed Nailed it! Totally agree. I like having the `shouldTruncateText` prop and top align when not truncated idea. That prop makes the component more flexible and useful.
