### ISSUE TITLE
AccountProfileInfo component

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction-component-library#250]
# AccountProfileInfo component

### Summary description of UI component
A component that shows an avatar image of a person on the left, with their name and email address on the right. It optionally also shows an Edit account button.

### Rationale for why this component is necessary
It appears in the upper corner of all profile pages in the starter kit, but could be used elsewhere.

### Images / Designs of UI component in context

<img width="338" alt="screenshot 2018-08-24 09 51 40" src="https://user-images.githubusercontent.com/3012067/44591507-8775d180-a783-11e8-9f5b-227312621ed2.png">

https://zpl.io/2ymPpwy

### React State
None

### Data Fetching
None. All data is from props.

### State Store
None. All data is from props.

### Routing / Query String
N/A

### Render Criteria
- Always shows the image. Should show a placeholder SVG if no image is provided in props.
- Shows the button only if requested. Does not show it by default.

#### Desktop, Tablet, Mobile
It should be full width of its container, with the content on the right side being left aligned.

#### Normal
See designs

#### Empty
Name and email address are required. Image is not required but should show a placeholder image. So there is no empty state.

#### Loading / retrieving data
N/A

#### Processing / Waiting for response
N/A

#### Error
N/A

#### Active (e.g. button is depressed)
N/A

#### Disabled
N/A

#### Focus
N/A

**Comment by kieckhafer** [comment]
@rymorgan @nnnnat @aldeed 

I'm wondering what we should do about the placeholder image / showing initials on the user profile.

In the `ViewerInfo` component, @nnnnat is using initials and a colored background. There is no image used at any point (provided, nor placeholder).

In this ticket, which is a similar component on a different page, the notes here say to use a provided profile image, or to use a placeholder image.

1) Should we make these both be the same, as in both use placeholder images or initials?
2) Should the `ViewerInfo` be using a photo if it's available
3) What should we use as a placeholder image. We currently use Gravatar on the meteor app. I understand not wanting a dependency on gravatar here, but I know one of @rymorgan's concerns is that people most likely won't upload an image for an ecommerce site, so we want something that isn't just a default one-size-fits-all placeholder, so it still looks nice.

Thoughts?

**Comment by rymorgan** [comment]
I suppose another thing we can do is a random pattern graphic or something. I think it's pretty lame to show a user icon unless that icon is there to encourage folks to upload a photo. I also think in the future we should pull in a photo for those that use a social sign on.

**Comment by aldeed** [comment]
My 2c is that the component should use a provided image URL prop, and fall back to the initials the same as ViewerInfo if no image URL is provided. I recommend pulling the avatar piece out of `ViewerInfo` so that you can share the avatar component in both places.

I do think the starter kit should use Gravatar, but that is simply a way of retrieving an image based on an email address. So it can happen outside of the component and the response URL can be passed in.

**Comment by kieckhafer** [comment]
@aldeed Sounds good. There actually isn't any avatar piece inside ViewerInfo, it's strictly the initials with no images. So we'll need to do the opposite, I'll make the avatar separate in this PR, and then once this is pulled in, we can put the avatar piece into the ViewerInfo component.

**Comment by aldeed** [comment]
@kieckhafer Right, but that logic that is figuring out and rendering the initials should be moved to the new avatar component. It should be used when the image URL is null.
