### ISSUE TITLE
Select component triggers `onChange` when being mounted

### ISSUE THREAD

**Issue by ajporlante** [reactioncommerce/reaction-component-library#266]
Type: **minor**

**Describe the bug**
Select component triggers `onChange` when being mounted.

**To Reproduce**
Use Select component and set an `onChange` prop. The function will be triggered even when user has not interacted with it yet.

**Expected behavior**
Do not trigger `onChange` when being mounted.

**Additional context**
Possibly because of this line: 

https://github.com/reactioncommerce/reaction-component-library/blob/429854e4522e973c757c5d44185444b9a08d5be4/package/src/components/Select/v1/Select.js#L456

When mounting, `lastValue` is always `undefined`.

**Comment by aldeed** [comment]
@ajporlante This is intended behavior and is actually a requirement of the form spec that we're adhering to. In most situations it is helpful because it allows the parent to easily track state. What problem is it causing for you?

**Comment by ajporlante** [comment]
@aldeed I guess I'm just not aware that it is indeed the intended design. I'll see if I can find workarounds to solve my problem and get back to you if the design is prohibiting me to do something important.

**Comment by ajporlante** [comment]
Closing this as I found the way to solve my problem.
