### ISSUE TITLE
Bug: Select: UX - Up and down keyboard arrows should work in Select

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-component-library#286]
Type: **minor**

**Describe the bug**
When a user is clicking in the Select, they should be able to use the up and down keyboard arrows to scroll up and down through the Select options.

Try a Select on the React-Select demo site: https://react-select.com/home and try it on Component Library. Using the up/down arrow keys works fine on React-Select site.

**To Reproduce**
1. https://stoic-hodgkin-c0179e.netlify.com/#!/Select
2. Click on a select
3. Use up and down keyboard arrows

**Expected behavior**
The Select focus should change according to the up/down arrow keyboard pushing

**Comment by aldeed** [comment]
This is actually a styles bug only. If you do the reproduction steps and actually press Enter to select after pushing up or down, it does select as you would expect. So we're just missing the color/highlight styling of the currently focused option

**Comment by spencern** [comment]
I noticed this bug as well when navigating through the app.
