### ISSUE TITLE
Bug: Minicart - Add the padding on the sides back

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-component-library#288]
Type: **minor**

**Describe the bug**
<img width="485" alt="screen shot 2018-09-18 at 4 13 53 pm" src="https://user-images.githubusercontent.com/3673236/45721671-e13ca200-bb5d-11e8-9de5-696ad2d46640.png"> vs.
<img width="346" alt="screen shot 2018-09-18 at 4 13 58 pm" src="https://user-images.githubusercontent.com/3673236/45721672-e13ca200-bb5d-11e8-9812-cab8ba5d932a.png">

**Comment by spencern** [comment]
@rosshadden I also saw that occasionally this component gets aligned too far to the right. This may be a starter kit issue and I can file a new issue if it's unrelated to what you're working on.

<img width="406" alt="image" src="https://user-images.githubusercontent.com/1203639/45853043-521bbf80-bd00-11e8-9f6b-030cfd8a9452.png">
