### ISSUE TITLE
Spinners and Loading Bars - Design & Usage Guidelines

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction-component-library#29]
As a developer for Reaction or a member of the Reaction community, I should be able to get design guidelines on a component level for the spinners and loading bar component.

**Comment by aldeed** [comment]
I have some specific questions here with regard to current work on buttons and forms:

- while it’s action is occurring, in addition to a button being disabled, should a spinner be shown in place of the button text? next to the button? overlaid somewhere else on the screen?
- what should the “spinner” be?
- on forms, if there’s a submit button spinner, is there also any additional busy indicator (e.g., superimposed

**Comment by cassytaylor** [comment]
@aldeed, Here's the documentation for what we're calling the "button state spinner" (the spinner that would appear within a button). We'll update this file with other spinners soon!

To answer your questions-
- We'd like the spinner to be shown in conjunction with the button text, to the right (within the button). This means the button will have to expand during the "spinner state" to accommodate the spinner.
- The spinner (for now) is kinda a generic broken circle that would rotate until loading completes.. you can download it from Zeplin (just click on the spinner and you should see the download options.) There's a chance that it might "wobble" during the rotation animation... let me know if this happens!
- The way we've defined it is that the button state spinner and page/container overlay spinner should be mutually exclusive... ie, you'd only use one or the other. 

http://zpl.io/agG77J9

![spinner - guidelines](https://user-images.githubusercontent.com/36006187/37937384-a6ef49a8-3116-11e8-9972-d310509f06c0.png)

And here's an animation of the button state spinner-
![ezgif-5-63cfea07ae](https://user-images.githubusercontent.com/36006187/37937402-bb32e532-3116-11e8-876c-397013967ca3.gif)
better quality -> https://drive.google.com/file/d/1b1x8EYEcNvb3fGxx0ULktqcoJhh8JFQ3/view?usp=sharing
