### ISSUE TITLE
Grid images not sized correctly

### ISSUE THREAD

**Issue by dancastellon** [reactioncommerce/reaction-component-library#293]
Type: **minor**

**Describe the bug**
Some images in the grid are not sized correctly. Landcape images are fine, but portrait images appear as rectangles inside the square. See the screenshot below.

**To Reproduce**
1. Visit the starterkit with the sample data
2. Observe portrait images not being sized correctly

**Expected behavior**
If an image is landscape, nothing needs to be changed. But if an image is portrait, the `fit` prop on the `ProgressiveImage` component within the grid should be set to `contain`.

**Screenshots**
![incorrect-image-sizing](https://user-images.githubusercontent.com/849570/45842402-a7e56d00-bcea-11e8-89c5-1d49b60b833f.jpg)

**Comment by spencern** [comment]
I don't know that we want the UI component to be making the decision to crop an image. @rymorgan any thoughts on this?

**Comment by dancastellon** [comment]
@spencern My fix just essentially makes the grid work as it did before, emulating the `background-position` style it used to have. Basically, if landscape, `width: auto; height: 100%`, if portrait `width: 100%; height: auto`.

**Comment by aldeed** [comment]
There's definitely a larger question we need to have about image cropping. Ideally the operator could crop the various necessary ratios manually using a cropping UI as part of the initial upload. But for now I think we need this to match the behavior of the existing grid in Meteor UI.

**Comment by rymorgan** [comment]
I don't know how huge of an issue it is either way though b/c stores will all have a set ratio that they crop all their images too so they all align. A bulk cropping tool could be cool. We'd need to ask around to see how big of a need this is though b/c most of the stores are probably producing images through photo shoots or from getting them manufacturers and cropping and exporting them from image sofware like Lightroom.
