### ISSUE TITLE
Colors: Add lighten and darken mixins

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-component-library#343]
Type: **minor**

Add `lighten` and `darken` color utility methods to create colors like:

- Warning
border: #E6DBBE
background: #FEF9ED

- Info
border: #C4E3F6
background: #F5FBFE

- Success
border: #BCDFD2
background: #EDFCF8

- Error
border: #F4C9CC
background: #FEF6F7

For now, library users can change colors with the InlineAlert variables.

**Comment by aldeed** [comment]
Early on we had a dependency on [polished](https://polished.js.org/docs/) and I tried to make the button component do automatic lighten/darken, but talking with @rymorgan we decided that it wasn't producing good results and it's hard to automatically determine proper text contrast on top of that.

If everything is a variable, users of the components could depend on something like `polished` and use that to set the theme variables. I'm not sure what beyond that is the proposal in this issue.
