### ISSUE TITLE
Tag and Tag Editing - Design & Usage Guidelines

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction-component-library#35]
As a developer for Reaction or a member of the Reaction community, I should be able to get design guidelines on a component level for the tag and tag editing component.

**Comment by cassytaylor** [comment]
Tag guidelines are on Zeplin here - http://zpl.io/adA6WKE

![tags - guidelines](https://user-images.githubusercontent.com/36006187/37545005-b0a6f082-292c-11e8-8788-8cd36f326f46.png)
