### ISSUE TITLE
Create a ThirdPartyButton component

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/reaction-component-library#351]
# ThirdPartyButton

### Summary description of UI component
ThirdPartyButton would be a simple full-width button that can connect a click event to a third party service (checkout with PayPal, sign in with Facebook, ApplePay, etc). 

### Images / Designs of UI component in context
![screen shot 2018-10-31 at 9 06 30 am](https://user-images.githubusercontent.com/1135948/47793501-633af180-dcec-11e8-9e31-81a346f650fe.png)
![screen shot 2018-10-31 at 9 07 09 am](https://user-images.githubusercontent.com/1135948/47793502-63d38800-dcec-11e8-82aa-9d8cf90b0223.png)

### Render Criteria
Possible props
```
{
  serviceType: PropTypes.oneOf("paypal", "applepay", "facebook").isRequired,
  onClick: PropTypes.func.isRequired
}
```

#### Active (e.g. button is depressed)
TBD

#### Disabled
TBD

#### Focus
TBD

**Comment by aldeed** [comment]
The last time I did any payment integrations (which has been a couple years), these buttons were provided by the payment lib and you were required to use their button. I assume that's still the case.

I think it would be best to actually do the PayPal integration to see whether this button component is needed. Most likely the PayPal-provided button will be used directly.

PayPal client-side integration demo: https://demo.paypal.com/us/demo/go_platform/pcRestClientSide/home
Docs: https://developer.paypal.com/docs/checkout/

**Comment by zenweasel** [comment]
Don't you still need to have a payment method selector?

@ajporlante Has already finished the Paypal integration if you want to see it.

**Comment by machikoyasuda** [comment]
@zenweasel Are you talking about the ticket for this component? https://github.com/reactioncommerce/reaction-component-library/issues/352

**Comment by zenweasel** [comment]
@machikoyasuda Yep, disregard my comment.

**Comment by machikoyasuda** [comment]
Probably not needed / Closing for now.
