### ISSUE TITLE
Create a PaymentCheckoutAction component

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/reaction-component-library#352]
# PaymentCheckoutAction

### Summary description of UI component
The PaymentCheckoutAciton component needs to display a "primary" payment method UI as well as an "other methods" section that will allow us to display PayPal, ApplePay, etc payment methods alongside the shops primary one.
  *  The "primary" payment component could be the StripeForm or any other type of credit card form UI
  * The "other methods" would just be a SelectableList with all the services as options.

### Rationale for why this component is necessary
Currently, the component library has only one payment checkout component and it's tightly coupled to the stripe payment service. We need a more flexible way to display payment options/forms from an array of payment services. 

### Images / Designs of UI component in context
![screen shot 2018-10-31 at 9 25 34 am](https://user-images.githubusercontent.com/1135948/47794783-26bcc500-dcef-11e8-9494-ad7891a166b3.png)
![screen shot 2018-10-31 at 9 25 46 am](https://user-images.githubusercontent.com/1135948/47794784-26bcc500-dcef-11e8-887e-99e38bf87643.png)

### Render Criteria
I see this component being very similar to the current StripePaymentCheckoutAction component and might just need to be a refactor/renaming of that component.

**Comment by machikoyasuda** [comment]
CheckoutActions object needs to take more than 1 mutation:

```diff
  {
    id: "3",
    activeLabel: "Enter payment information",
    completeLabel: "Payment information",
    incompleteLabel: "Payment information",
    status: "incomplete",
    component: PaymentCheckoutAction,
-    onSubmit: setPayment,
+    onSubmit: [setPaymentStripe, setPaymentPayPal],
    props: {
      payment: cart.checkout.payments[0]
    }
  },
```
