### ISSUE TITLE
Save button remains disabled after errored payment

### ISSUE THREAD

**Issue by ajporlante** [reactioncommerce/reaction-component-library#358]
Type: **minor**

**Describe the bug**
Save button remains disabled after errored payment

**To Reproduce**
1. Create a cart and checkout. Fill in the shipping address and select a shipping option.
2. In credit card form, force a Stripe error by using 4000000000000002 as credit card number.
3. Payment will fail and error message will be shown in the checkout page.
4. Now try to fill in credit card info again. 
5. See that the Save button remains disabled.

**Expected behavior**
Save button should be enabled when user re-enters complete credit card info.

**Comment by machikoyasuda** [comment]
Hey @ajporlante -

I wasn't able to reproduce this bug locally. Here's what my screen looks like after I entered `4000000000000002` with correct CVC, expiration date and zip code, and _then_ entered all correct data:
<img width="836" alt="screen shot 2018-11-05 at 5 08 13 pm" src="https://user-images.githubusercontent.com/3673236/48036519-9e3e8a00-e11d-11e8-99ef-bf3f3716242c.png">

After I entered a zip code that was long enough, the `Save` button was re-enabled.

If I enter incorrect zips, CVC or an expiration date, it will not trigger the `Save` button to be enabled:

<img width="811" alt="screen shot 2018-11-05 at 5 12 02 pm" src="https://user-images.githubusercontent.com/3673236/48036677-47858000-e11e-11e8-9b74-04db2f5f64cf.png">

<img width="754" alt="screen shot 2018-11-05 at 5 11 24 pm" src="https://user-images.githubusercontent.com/3673236/48036693-553b0580-e11e-11e8-86c7-8f7f3d7873be.png">

**Comment by ajporlante** [comment]
Yeah, I can verify that this issue is non-issue, the ZIP code just have to be long enough so the button becomes enabled again. Thanks!
