### ISSUE TITLE
Sortable Table - Design & Usage Guidelines

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction-component-library#37]
As a developer for Reaction or a member of the Reaction community, I should be able to get design guidelines on a component level for the sortable table component.

**Comment by cassytaylor** [comment]
Sortable table design guidelines are available on Zeplin here - http://zpl.io/agG4x1R
 
![sortable table - guidelines](https://user-images.githubusercontent.com/36006187/37479629-b94e04c2-2842-11e8-90f0-7a2693ae8be4.png)
