### ISSUE TITLE
Style guide architecture

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction-component-library#4]
Create architectural diagram for the style guide. 

Goals: 

- Stakeholder agreement on approach
- Get different teams/individuals/community on the same page as to our approach

**Comment by zenweasel** [comment]
minimalist apparently

**Comment by rymorgan** [comment]
Internal link to diagram: https://www.lucidchart.com/documents/edit/6faea839-a7d7-4420-a006-c3e384bfc97d/0

PNG form: 
![style guide - style guide architecture](https://user-images.githubusercontent.com/20409254/36224208-c04b9de4-117b-11e8-8d49-5e98ca158397.png)

**Comment by machikoyasuda** [comment]
Closing
