### ISSUE TITLE
Add back root yarn.lock

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction-component-library#414]
https://github.com/reactioncommerce/reaction-component-library/pull/413 removed both `yarn.lock` files but the root file is for the style guide website and as such I don't think it should be removed or ignored.

I'm not totally certain the PR was necessary in the first place since the build script only moves certain files into the final `dist` folder that is published to NPM, and I did not think `yarn.lock` was one that is moved and published, but I could be wrong about that. Either way, removing that one shouldn't harm anything.

@focusaurus

**Comment by focusaurus** [comment]
Yeah I wasn't aware that [yarn only looks at the top-level yarn.lock when running yarn install](https://yarnpkg.com/lang/en/docs/yarn-lock/#toc-current-package-only) so our endless snyk loops must be caused by something else.
