### ISSUE TITLE
Use core-js 3 or change production build

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction-component-library#432]
Using this module will fail if I change the babel configuration of the storefront to use core-js 3 due to missing imports which seem to be from core-js 2.

Forking the component library and upgrading to core-js 3 was a fairly simple process which resolved my issue.

It would be great to either:

1. ) Update this project to use core-js 3 (and recheck storefront compatibility / update that one aswell)

2. ) Make sure the production build doesn't rely on core-js imports anymore.

**Comment by aldeed** [comment]
I think essentially this project needs to do the changes talked about [here](https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md#babelpolyfill)

**Comment by aldeed** [comment]
I'm not exactly sure why the version of core-js used to build the library package would matter, but perhaps because of the `useBuiltIns` setting. We need to do a build and then examine the output files to see where "core-js" requires are being added. i.e., prefer option 2 in this issue description.

**Comment by aldeed** [comment]
I believe #433 will resolve this
