### ISSUE TITLE
Color  variables

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction-component-library#53]
Define base colors w/ variables for button states, alerts, notification etc.

**Comment by rymorgan** [comment]
zpl.io/bW1nJBe

![color](https://user-images.githubusercontent.com/20409254/36875891-1a1ff2b0-1d67-11e8-86d1-98660c8dfbc9.png)

**Comment by nnnnat** [comment]
While I was adding these variables to the component lib I noticed a few hex values are the same for different colors, I used a color pick to get the hex but wanted to verify I've got the right colors.

@black30 #b3b3b3;
@black65 #595959;
@black #000000;
