### ISSUE TITLE
Create button component

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction-component-library#63]
**Summary**
Create a Button component for the component library.

**Implementation**
The Button component should follow the designs in #10. @aldeed has already done a significant amount of work towards completing this issue and this issue can serve as a reference for how to add components to the library.

**Acceptance Criteria**
- This will add a `Button/v1` section to the component library
- The Button will be included in the `Button.js` file
- The Button component be accompanied by documentation in the `Button.md` file
- The Button component will be well tested within the `Button.test.js` file

**Comment by rymorgan** [comment]
I made two small additions/variations for the button component. More details here: https://github.com/reactioncommerce/reaction-component-library/issues/10

**Comment by aldeed** [comment]
@rymorgan I will add `secondaryDanger` type. As for dropdown button, we'll make that its own component in a future ticket.
