### ISSUE TITLE
Divider component

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction-component-library#65]
**Summary**
Create a Divider component for the component library.

**Implementation**
The Divider component should fit the usage case shown in the reactioncommerce/reaction#3907
Work with @rymorgan to define any potential use cases that this component might have outside of the scope of reactioncommerce/reaction#3907

**Acceptance Criteria**
- This will add a `Divider/v1` section to the component library
- The Divider will be included in the `Divider.js` file
- The Divider component be accompanied by documentation in the `Divider.md` file
- The Divider component will be well tested within the `Divider.test.js` file

**Comment by rymorgan** [comment]
@mikemurray This is one of the components I wasn't sure what it did, can you tell me where we use this component? Is it simply a rule? Or is it a more structural element?

**Comment by rymorgan** [comment]
@spencern got it! I was thinking it was an existing component.

**Comment by kieckhafer** [comment]
@spencern 

Our existing Divider component uses our `Translation` component.

Do we want to do something similar, using a new Translation component?

If so, I think this ticket is blocked until the Translation component is created.

If not, how do we want to do this?

**Comment by mikemurray** [comment]
@kieckhafer I believe we won't be handling translations same way we do with the older components. So for now, just make it a prop for the label that and let the parent component decide what text, translated or not, will show up in the divider.

**Comment by spencern** [comment]
Yep, what @mikemurray said.

**Comment by kieckhafer** [comment]
Sounds good, thanks @mikemurray / @spencern

**Comment by spencern** [comment]
@mikemurray if you're not actively working on this, I think we should suspend work on it for now and move it out of this sprint.

**Comment by aldeed** [comment]
Closing until such time as this is actually needed
