### ISSUE TITLE
Form component

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-component-library#7]
@efalayi commented on [Mon Nov 27 2017](https://github.com/reactioncommerce/reaction-docs/issues/378)

- What are the props in the Form component used for?
- What props are compulsory?
- What props can be overridden?
- What is the type of value expected in each prop?
- Can the schema prop have a branched data?
- How can the form component  accommodate branched schema data?
- How can it be done to place form elements side by side?

---

@prinzdezibel commented on [Tue Dec 12 2017](https://github.com/reactioncommerce/reaction-docs/issues/378#issuecomment-351101728)

Could be that our own Component.Form will be superseded by http://forms.dairystatedesigns.com/reacto-form/ at some day in future. Not sure about the scope of both initiatives, though..

**Comment by aldeed** [comment]
When I tackle removing the remaining autoforms next, I will be most likely switching to using the `Form` component exported from ReactoForm as @prinzdezibel said. (I've experimented a bit already.) It's already pretty similar to Component.Form, but it will simplify a bunch of things. I will document this properly in the style guide as part of that ticket (https://github.com/reactioncommerce/reaction/issues/3034)

**Comment by spencern** [comment]
Closing in favor of #60
