### ISSUE TITLE
Style Guide Sitemap

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction-component-library#8]
Create sitemap for style guide

Goals: 
- Define navigation requirements
- Define how we will document components
- Define how we will document design guidelines
- Define what additional resources for style guide

**Comment by rymorgan** [comment]
Internal link:
https://www.lucidchart.com/documents/edit/6faea839-a7d7-4420-a006-c3e384bfc97d/2

.png format: 
![style guide - style guide sitemap](https://user-images.githubusercontent.com/20409254/36224615-03389ec6-117d-11e8-9157-0a7d0ef6d8dc.png)

**Comment by machikoyasuda** [comment]
Closing
