### ISSUE TITLE
Style the style guide

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction-component-library#84]
Need to adjust CSS, create some custom components, and add a standard header to make this look more like our www and docs sites.

Refer to:
- https://react-styleguidist.js.org/docs/cookbook.html#how-to-change-styles-of-a-style-guide
- https://react-styleguidist.js.org/docs/cookbook.html#how-to-change-the-layout-of-a-style-guide

- Sidebar
- Header bar
- Search bar
- Type font
- Code font
- `VIEW CODE`, `PROPS` text type
- Table type
- Code block type

**Comment by rymorgan** [comment]
Some details may need to be updated here but I already designed these pages out a while ago and are consistent with the design direction we are taking on the docs in general. 

https://zpl.io/bLNB1gG

![sg - layout code](https://user-images.githubusercontent.com/20409254/41493214-dcc18e78-70b9-11e8-8e5e-8dcde5091e80.png)
![sg - layout usage](https://user-images.githubusercontent.com/20409254/41493215-dcde3df2-70b9-11e8-93d7-a1da3c550436.png)
