### ISSUE TITLE
Feature: Process - Publish the style guide to a static site

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction-component-library#85]
Type: **need-to-have**
Type: **feature**

## Issue

Overwrite styleguide.reactioncommerce.com since that is no longer correct, and hook up the `styleguide:build` process into `semantic-release` with CI.

## Proposed solution

- On every push to `master`, build the site with `yarn run styleguide:build` and publish those contents to `styleguide.reactioncommerce.com` via Netlify. This should trigger a Slack notification on deploy success.

- It can be triggered on CI at the same time as `semantic-release` (on every push to master), but it should publish the static site every time (whereas `semantic-release` may or may not actually publish a new version). Once you're comfortable with the process, it should build straight to the prod URL. There is no need for managing multiple versions or anything like that, so it should be safe and simple.

**Comment by machikoyasuda** [comment]
@ticean @impactmass - Let's use Netlify for this  🎉 I believe https://styleguide.reactioncommerce.com/ is the last site on the old infrastructure.

**Comment by machikoyasuda** [comment]
@ticean @impactmass @aldeed - Since the NPM packages are auto-released w/ semantic release, should we also tie a docs release w/ every semantic release? Makes the most sense to me.

We can first start by testing it on a URL like `https://staging-styleguide.reactioncommerce.com/` before the real deal, `https://styleguide.reactioncommerce.com/`.

**Comment by aldeed** [comment]
@machikoyasuda I think it can be triggered on CI at the same time as semantic-release (on every push to master), but it should publish the static site every time (whereas semantic-release may or may not actually publish a new version). Once you're comfortable with the process, it should build straight to the prod URL. There is no need for managing multiple versions or anything like that, so it should be safe and simple.

**Comment by machikoyasuda** [comment]
Master is now being deployed to: https://stoic-hodgkin-c0179e.netlify.com/
