### ISSUE TITLE
Style guide wire frame and visual design 

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction-component-library#9]
As a contributor to Reaction Commerce, both core contributors or community contributors, I should be able to view a style guide that has:

- design guidelines for components,
- visual representation of our components with properties,
- the ability to select between our most common usages (i.e. buttons types)
- ability to copy react code
- design principles (now) and color, typography, and illustration guidelines (in the future).

**Comment by rymorgan** [comment]
Wireframes: 
Internal link: https://www.lucidchart.com/documents/edit/6faea839-a7d7-4420-a006-c3e384bfc97d/3
PNG format: 
![style guide - style guide wireframe](https://user-images.githubusercontent.com/20409254/36224979-0cfc53b6-117e-11e8-9102-a54b3a4ce15f.png)

**Comment by rymorgan** [comment]
Visual design
Zeplin links:
Design guidelines/usage tab - zpl.io/bLNB1gG
Code/props tab - zpl.io/bLNN5XM

Screenshots: 
Usage -
![sg - layout usage](https://user-images.githubusercontent.com/20409254/36225128-89b149e8-117e-11e8-93a7-c3a1c1aeb36a.png)
Code - 
![sg - layout code](https://user-images.githubusercontent.com/20409254/36225136-9321456e-117e-11e8-9091-b0f87f257bdd.png)

**Comment by machikoyasuda** [comment]
Closing for now
